export const FIRST_ANSWER_MULTIPLIER = 1.2;

export const DEFAULT_DELAY = 1000;
export const SHORT_DELAY = 250;
export const TIME_BETWEEN_QUESTIONS_TEST_MODE = 3000;
export const MINIMAL_TIME_FOR_PANIC_MODE_QRL = 20;
export const MINIMAL_TIME_FOR_PANIC_MODE_DEFAULT = 10;
export const QRL_DURATION = 60;

export const ID_LOBBY_LENGTH = 4;
export const ID_GAME_PLAYED_LENGTH = 10;
export const TIME_HISTOGRAM_UPDATE = 5000;
export const NOT_FOUND_INDEX = -1;
export const LAUNCH_TIMER_DURATION = 5;

export const MINIMUM_QUESTIONS_FOR_RANDOM_MODE = 5;
